remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

lang: en-US
title: Broderick Westrope | Digital Portfolio
email: broderickwestrope@gmail.com
description: "Software Engineering Portfolio"
author:
  name: Broderick Westrope
  twitter: broderiiick
  # picture: /assets/images/johndoe.png
twitter_username: broderiiick
github_username: Broderick-Westrope
